version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    environment:
      MONGO_URI: "mongodb://mongo:27017/surveys_db"
      POSTGRES_URI: "postgresql://postgres:postgres@postgres:5432/surveys_db"
      REDIS_URI: "redis://redis:6379"
    depends_on:
      - mongo
      - postgres
      - redis

  mongo:
    image: mongo:5
    ports:
      - "27017:27017"

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: surveys_db
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"
