FROM python:3.11  
# Instala dependencias necesarias
RUN pip install confluent_kafka pymongo 

# Define el directorio de trabajo
WORKDIR /app

# Copia todos los archivos del contexto de construcción a la imagen
COPY . .

# Ejecuta el consumidor
CMD ["python", "consumer.py"]
