version: '3'

services:
  app:
    build: .
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: tareauno
      DB_USER: postgres
      DB_PASSWORD: mysecretpassword
      SECRET_KEY: mysecretkey
    ports:
      - 5002:5000
    networks:
      - web
    depends_on:
      - db
    volumes:
      - .:/opt/app
    command: poetry run python3 -m flask --app app.py --debug run --host=0.0.0.0

  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    networks:
      - web
    volumes:
      - ./database/:/docker-entrypoint-initdb.d/

networks:
  web:
    driver: bridge